### ISSUE TITLE
 Call to undefined function GuzzleHttp\Psr7\uri_for()

### ISSUE THREAD

**Issue by edhelas** [ratchetphp/Pawl#134]
Since the latest Pawl upgrade I have this issue:

```
[2021-12-14T11:55:15.243983+00:00] movim.ERROR: Error: Call to undefined function GuzzleHttp\Psr7\uri_for() in /var/www/html/movim/vendor/ratchet/pawl/src/Connector.php (line 126) Trace 
#0 /var/www/html/movim/vendor/ratchet/pawl/src/Connector.php(38): Ratchet\Client\Connector->generateRequest() 
#1 /var/www/html/movim/linker.php(324): Ratchet\Client\Connector->__invoke() 
#2 {main} [] []
```

**Comment by cboden** [comment]
Hmm, that's odd. v0.4.1, which was just tagged uses the updated method `uriFor` as [seen here](https://github.com/ratchetphp/Pawl/blob/master/src/Connector.php#L127). 

What's the output of `composer show`?

**Comment by edhelas** [comment]
```
$ composer show
cakephp/core                         4.3.2     CakePHP Framework Core classes
cakephp/database                     4.3.2     Flexible and powerful Database abstraction library with a familiar ...
cakephp/datasource                   4.3.2     Provides connection managing and traits for Entities and Queries th...
cakephp/utility                      4.3.2     CakePHP Utility classes such as Inflector, String, Hash, and Security
cboden/ratchet                       v0.4.4    PHP WebSocket library
cocur/slugify                        v4.0.0    Converts a string into a slug.
composer/ca-bundle                   1.3.1     Lets you find a path to the system CA bundle, and includes a fallba...
composer/package-versions-deprecated 1.11.99.4 Composer plugin that provides efficient querying for installed pack...
defuse/php-encryption                v2.3.1    Secure PHP Encryption Library
dflydev/fig-cookies                  v3.0.0    Cookies for PSR-7 HTTP Message Interface.
doctrine/cache                       2.1.1     PHP Doctrine Cache library is a popular cache implementation that s...
doctrine/dbal                        3.2.0     Powerful PHP database abstraction layer (DBAL) with many features f...
doctrine/deprecations                v0.5.3    A small layer on top of trigger_error(E_USER_DEPRECATED) or PSR-3 l...
doctrine/event-manager               1.1.1     The Doctrine Event Manager is a simple PHP event system that was bu...
doctrine/inflector                   2.0.4     PHP Doctrine Inflector is a small library that can perform string m...
embed/embed                          3.4.17    PHP library to retrieve page info using oembed, opengraph, etc
evenement/evenement                  v3.0.1    Événement is a very simple event dispatching library for PHP
ezyang/htmlpurifier                  v4.13.0   Standards compliant HTML filter written in PHP
fabiang/sasl                         v1.0.3    Abstraction of various SASL mechanism responses.
guzzlehttp/psr7                      2.1.0     PSR-7 message implementation that also provides common utility methods
illuminate/bus                       v8.75.0   The Illuminate Bus package.
illuminate/collections               v8.75.0   The Illuminate Collections package.
illuminate/container                 v8.75.0   The Illuminate Container package.
illuminate/contracts                 v8.75.0   The Illuminate Contracts package.
illuminate/database                  v8.75.0   The Illuminate Database package.
illuminate/events                    v8.75.0   The Illuminate Events package.
illuminate/macroable                 v8.75.0   The Illuminate Macroable package.
illuminate/pipeline                  v8.75.0   The Illuminate Pipeline package.
illuminate/support                   v8.75.0   The Illuminate Support package.
league/commonmark                    1.6.6     Highly-extensible PHP Markdown parser which fully supports the Comm...
monolog/monolog                      2.3.5     Sends your logs to files, sockets, inboxes, databases and various w...
nesbot/carbon                        2.55.2    An API extension for DateTime that supports 281 different languages.
paragonie/random_compat              v9.99.100 PHP 5.x polyfill for random_bytes() and random_int() from PHP 7
psr/cache                            1.0.1     Common interface for caching libraries
psr/container                        1.1.2     Common Container Interface (PHP FIG PSR-11)
psr/http-factory                     1.0.1     Common interfaces for PSR-7 HTTP message factories
psr/http-message                     1.0.1     Common interface for HTTP messages
psr/log                              1.1.4     Common interface for logging libraries
psr/simple-cache                     1.0.1     Common interfaces for simple caching
rain/raintpl                         3.1.1     easy and fast template engine
ralouphie/getallheaders              3.0.3     A polyfill for getallheaders.
ratchet/pawl                         v0.3.5    Asynchronous WebSocket client
ratchet/rfc6455                      v0.3.1    RFC6455 WebSocket protocol handler
react/cache                          v1.1.1    Async, Promise-based cache interface for ReactPHP
react/child-process                  v0.6.4    Event-driven library for executing child processes with ReactPHP.
react/dns                            v1.8.0    Async DNS resolver for ReactPHP
react/event-loop                     v1.2.0    ReactPHP's core reactor event loop that libraries can use for event...
react/http                           v1.5.0    Event-driven, streaming HTTP client and server implementation for R...
react/promise                        v2.8.0    A lightweight implementation of CommonJS Promises/A for PHP
react/promise-stream                 v1.3.0    The missing link between Promise-land and Stream-land for ReactPHP
react/promise-timer                  v1.8.0    A trivial implementation of timeouts for Promises, built on top of ...
react/socket                         v1.10.0   Async, streaming plaintext TCP/IP and secure TLS socket server and ...
react/stream                         v1.2.0    Event-driven readable and writable streams for non-blocking I/O in ...
respect/stringifier                  0.2.0     Converts any value to a string
respect/validation                   2.2.3     The most awesome validation engine ever created for PHP
ringcentral/psr7                     1.3.0     PSR-7 message implementation
robmorgan/phinx                      0.12.9    Phinx makes it ridiculously easy to manage the database migrations ...
symfony/config                       v5.4.0    Helps you find, load, combine, autofill and validate configuration ...
symfony/console                      v5.4.1    Eases the creation of beautiful and testable command line interfaces
symfony/deprecation-contracts        v2.5.0    A generic function and convention to trigger deprecation notices
symfony/filesystem                   v5.4.0    Provides basic utilities for the filesystem
symfony/http-foundation              v5.4.1    Defines an object-oriented layer for the HTTP specification
symfony/polyfill-ctype               v1.23.0   Symfony polyfill for ctype functions
symfony/polyfill-intl-grapheme       v1.23.1   Symfony polyfill for intl's grapheme_* functions
symfony/polyfill-intl-normalizer     v1.23.0   Symfony polyfill for intl's Normalizer class and related functions
symfony/polyfill-mbstring            v1.23.1   Symfony polyfill for the Mbstring extension
symfony/polyfill-php73               v1.23.0   Symfony polyfill backporting some PHP 7.3+ features to lower PHP ve...
symfony/polyfill-php80               v1.23.1   Symfony polyfill backporting some PHP 8.0+ features to lower PHP ve...
symfony/polyfill-php81               v1.23.0   Symfony polyfill backporting some PHP 8.1+ features to lower PHP ve...
symfony/routing                      v5.4.0    Maps an HTTP request to a set of configuration variables
symfony/service-contracts            v2.5.0    Generic abstractions related to writing services
symfony/string                       v5.4.0    Provides an object-oriented API to strings and deals with bytes, UT...
symfony/translation                  v5.4.1    Provides tools to internationalize your application
symfony/translation-contracts        v2.5.0    Generic abstractions related to translation
voku/portable-ascii                  1.5.6     Portable ASCII library - performance optimized (ascii) string funct...
```
Here we go

**Comment by edhelas** [comment]
My bad, Pawl was actually not upgraded. I changed my `composer.json` to put the latest version.

```
  - Upgrading ratchet/pawl (v0.3.5 => v0.4.1): Extracting archive
```

I'm curious to know why the `composer upgrade` didn't upgrade it automatically ?
