### ISSUE TITLE
Timing out inside Laravel's Event listener's

### ISSUE THREAD

**Issue by nd9600** [ratchetphp/Pawl#97]
Hi,

I've been trying to send a message to a Websocket server inside a [Laravel Event Listener](https://laravel.com/docs/5.8/events#defining-listeners), and every request times out, without any sort of connection being made on the server-side - this is the client-side stack trace:

```
Connection to tls://$WEBSSOCKET_URL:443 timed out after 20 seconds on /var/app/current/vendor/react/socket/src/TimeoutConnector.php at line #41   
#0 /var/app/current/vendor/react/promise/src/RejectedPromise.php(25): React\Socket\TimeoutConnector::React\Socket\{closure}(Object(React\Promise\Timer\TimeoutException))
#1 /var/app/current/vendor/react/promise/src/Promise.php(134): React\Promise\RejectedPromise->then(NULL, Object(Closure))
#2 /var/app/current/vendor/react/promise/src/Promise.php(168): React\Promise\Promise::React\Promise\{closure}(Object(React\Promise\RejectedPromise))
#3 /var/app/current/vendor/react/promise/src/Promise.php(148): React\Promise\Promise->settle(Object(React\Promise\RejectedPromise))
#4 /var/app/current/vendor/react/promise/src/Promise.php(237): React\Promise\Promise->reject(Object(React\Promise\Timer\TimeoutException))
#5 /var/app/current/vendor/react/promise-timer/src/functions.php(47): React\Promise\Promise::React\Promise\{closure}(Object(React\Promise\Timer\TimeoutException))
#6 /var/app/current/vendor/react/event-loop/src/Timer/Timers.php(96): React\Promise\Timer\{closure}(Object(React\EventLoop\Timer\Timer))
#7 /var/app/current/vendor/react/event-loop/src/StreamSelectLoop.php(183): React\EventLoop\Timer\Timers->tick()
#8 /var/app/current/vendor/ratchet/pawl/src/functions.php(28): React\EventLoop\StreamSelectLoop->run()
#9 [internal function]: Ratchet\Client\{closure}()
```

This is the code I was trying to run inside the Listener:

```php
$websocketURL = env("WEBSOCKET_URL");
connect($websocketURL)->then(function (WebSocket $connection) use ($websocketURL) {
    $connection->send("json-encoded data");
    $connection->on('message', function (MessageInterface $msg) use ($connection) {
        $connection->close();
    });
}, function (Exception $exception) {
    Log::error("{$exception->getMessage()} on {$exception->getFile()} at line #{$exception->getLine()}");
});
```

when I replaced it with this instead, it started working (using [this library](https://github.com/Textalk/websocket-php)):
```php
$websocketURL = env("WEBSOCKET_URL");
            
try {
    $client = new WebSocket\Client($websocketURL);
    $client->send("json-encoded data");
    $received = $client->receive();

    $client->close();

} catch (Exception $exception) {
    Log::error($exception->getTraceAsString());
}
```

Oddly, it worked fine inside [Laravel's Commands](https://laravel.com/docs/5.8/artisan#introduction).

**Comment by clue** [comment]
Thanks for reporting. I've just tried to reproduce this and it seems to work just fine on my end.

The error means that the underlying TCP/IP connection to the host did not complete and timed out while waiting for a response from the server side. As a first step, I would suggest checking the DNS records resolve to the correct IP, the host with this IP is actually up and that no firewall rules block this connection.

I hope this helps :+1:

**Comment by nd9600** [comment]
Sorry, I might have missed out important code there - the Listener needs to pull the Event off a database queue, I think.

I'm not sure if that trace above is actually the problem;
I've been trying this Listener now instead, and it fails completely silently:

```php
<?php
declare(strict_types=1);


namespace App\Listeners;


use Exception;
use function Ratchet\Client\connect;

class TestListener implements ShouldQueue
{
    public $connection = "database";
    
    function handle($event): void
    {
        try {
            $url = "ws://echo.socketo.me:9000";
            $url = "wss://echo.websocket.org";
            $url = "ws://demos.kaazing.com/echo";
            echo("connecting to $url\n");
            connect($url)->then(function ($conn) {
                echo("connected\n");
                $conn->on('message', function ($msg) use ($conn) {
                    echo("Received: {$msg}\n");
                    $conn->close();
                });
    
                echo("sending\n");
                $conn->send('Hello World!');
                echo("sent\n");
            }, function (Exception $e) {
                echo "{$e->getTraceAsString()}\n";
                echo "Could not connect: {$e->getMessage()}\n";
            });
        } catch (Exception $e) {
            echo "{$e->getTraceAsString()}\n";
            echo "Could not connect: {$e->getMessage()}\n";
        };
    }
}
```

Laravel just prints
```
[2019-07-26 13:18:57][555] Processing: App\Listeners\TestListener
connecting to ws://demos.kaazing.com/echo
[2019-07-26 13:18:57][555] Processed:  App\Listeners\TestListener
```

and never connects to the server, sends or receives anything, or closes.

This is the same no matter which of the 3 URLs are used.

At first I thought it was because `connect()` returns a Promise, and the Listener was finishing before the Promise resolved, but then I tried this, and it worked as expected:

```php
<?php
declare(strict_types=1);


namespace App\Listeners;


use Exception;
use Illuminate\Contracts\Queue\ShouldQueue;
use React\Promise\Deferred;
use React\Promise\PromiseInterface;

class TestListener implements ShouldQueue
{
    public $connection = "database";

    function getPromise(): PromiseInterface
    {
        $deferred = new Deferred();
        sleep(5);
        $deferred->resolve(1234);
        
        return $deferred->promise();
    }
    
    function handle($event): void
    {
        try {
            echo "getting promise\n";
            $this->getPromise()->then(function (int $i) {
                echo "i is: $i\n";
            }, function (Exception $e) {
                echo "{$e->getTraceAsString()}\n";
                echo "Could not connect: {$e->getMessage()}\n";
            });
        } catch (Exception $e) {
            echo "{$e->getTraceAsString()}\n";
            echo "Could not connect: {$e->getMessage()}\n";
        };
    }
}
```

**Comment by nd9600** [comment]
Maybe this shows it better:
```php
<?php
declare(strict_types=1);


namespace App\Listeners;


use Exception;
use Illuminate\Contracts\Queue\ShouldQueue;
use function Ratchet\Client\connect;

class TestListener implements ShouldQueue
{
    public $connection = "database";
    
    function handle($event): void
    {
        try {
            $url = "wss://echo.websocket.org";
            $url = "ws://demos.kaazing.com/echo";
            $url = "ws://echo.socketo.me:9000";
            echo("connecting to $url\n");
//            connect($url)->then(function ($conn) {
//                echo("connected\n");
//                $conn->close();
//                $conn->on('message', function ($msg) use ($conn) {
//                    echo("Received: {$msg}\n");
//                    $conn->close();
//                });
//
//                echo("sending\n");
//                $conn->send('Hello World!');
//                echo("sent\n");
//            }, function (Exception $e) {
//                echo "{$e->getTraceAsString()}\n";
//                echo "Could not connect: {$e->getMessage()}\n";
//            });
    
            $client = new \WebSocket\Client($url);
            echo("connected\n");
            echo("sending\n");
            $client->send("json-encoded data");
            echo("sent\n");
            $received = $client->receive();
            echo("received: $received\n");
    
            $client->close();
            echo("closed\n");
        } catch (Exception $e) {
            echo "{$e->getTraceAsString()}\n";
            echo "Could not connect: {$e->getMessage()}\n";
        };
    }
}
```

The commented-out code is this library, the bottom code is https://github.com/Textalk/websocket-php.
Both use the same URLs, but the top fails silently, and the bottom connects, sends, and receives a response.

**Comment by clue** [comment]
The `connect()` method provided by this library uses some magic to only start the loop at the end of the script. This means it doesn't really integrate well with your blocking example code. In other words: It will not actually run.

As an alternative, consider following the "more in-depth example" as given in the documentation (https://github.com/ratchetphp/Pawl#example). This allows you more control over when the loop should run (i.e. within your `handle()` method).

**Comment by nd9600** [comment]
Ok, thanks for your help
